# Site settings

# Plugins
gems:
  - kramdown
  - jekyll-babel # gem install jekyll-babel

# Build settings
markdown: kramdown

# Babel settings
babel_js_extensions: 'jsx'

# Sass settings
sass:
  sass_dir: _sass

# LiveReload setting
livereload: false # gem install guard, guard-jekyll, guard-livereload