# Site settings

# Plugins
gems: [kramdown]
livereload: true # gem install guard, guard-jekyll, guard-livereload

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: _sass

# LiveReload setting
livereload: true